import React from 'react';
import LegalOverlayLayout from './LegalOverlayLayout';
import LegalSection from './LegalSection';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TermsModal({ isOpen, onClose }: TermsModalProps) {
  return (
    <LegalOverlayLayout
      isOpen={isOpen}
      onClose={onClose}
      title="Terms of Service"
      subtitle="Last updated: May 20, 2026 • Platform usage terms and user rules"
      icon="description"
      acknowledgment="By entering this career workspace and starting your AI-guided journey, you confirm that you have read, understood, and agreed to these platform terms."
      copyright="© 2026 CareerTrack AI · Created with pride for ambitious candidates"
    >
      <div className="space-y-4">
        {/* Intro */}
        <div className="bg-primary/5 dark:bg-primary/10 border border-primary/10 rounded-2xl p-5 mb-2">
          <p className="text-xs md:text-[13px] text-on-surface leading-relaxed font-semibold">
            Welcome to <strong className="text-primary">CareerTrack AI</strong>! We are dedicated to providing modern, AI-powered career growth insights, resume analyses, and mock interview coaching. These Terms of Service outline your rights and obligations when using our platform.
          </p>
        </div>

        {/* Section 1 */}
        <LegalSection number={1} title="Platform Usage" icon="route" isOpen={true}>
          <p>
            CareerTrack AI is built to serve students, job seekers, and career transitioning professionals. We grant you a limited, non-exclusive, non-transferable, and revocable license to access our platform for your personal, educational, and non-commercial career development.
          </p>
          <p>
            You agree to access our workspaces solely through our official web interface and follow the guidance provided within the application flow.
          </p>
        </LegalSection>

        {/* Section 2 */}
        <LegalSection number={2} title="User Responsibilities" icon="face">
          <p>
            As a user, you agree to provide accurate and truthful information in your profile, resume details, and mock interviews. This is critical because our smart systems use your input to tailor your learning plans and generate insights.
          </p>
          <ul className="list-disc pl-5 space-y-1.5 mt-2">
            <li>Ensure uploaded resumes reflect your real background and qualifications.</li>
            <li>Maintain respectful communication and prompt behavior during mock interview simulations.</li>
            <li>Keep your profile data updated to get the most relevant career roadmap.</li>
          </ul>
        </LegalSection>

        {/* Section 3 */}
        <LegalSection number={3} title="Educational Purpose" icon="school">
          <p>
            All insights, mock interview scores, resume ATS advice, and career roadmaps generated by CareerTrack AI are intended for **educational and self-improvement purposes only**.
          </p>
          <p>
            While our systems utilize advanced algorithms to approximate standard ATS behaviors and industry expectations, our feedback does **not** guarantee specific employment outcomes, job offers, or successful recruitment results. Your decisions based on our recommendations are made at your own discretion.
          </p>
        </LegalSection>

        {/* Section 4 */}
        <LegalSection number={4} title="Account Security" icon="lock">
          <p>
            Your account credentials, such as email and password logins, are strictly confidential. You are solely responsible for all actions taken under your account.
          </p>
          <p>
            If you suspect any unauthorized access, security breach, or compromised login credentials, you agree to notify us immediately so we can help safeguard your career progress workspace.
          </p>
        </LegalSection>

        {/* Section 5 */}
        <LegalSection number={5} title="Acceptable Use" icon="gavel">
          <p>
            We are committed to fostering a safe, supportive, and ethical learning environment. You agree **not** to engage in the following prohibited activities:
          </p>
          <ul className="list-disc pl-5 space-y-1.5 mt-2">
            <li>Using automated scripts, bots, scraping, or web crawling tools to harvest profiles, data, or roadmaps.</li>
            <li>Submitting abusive, hateful, vulgar, or intentionally harmful prompts to the LLM-powered services.</li>
            <li>Attempting to bypass security barriers, reverse engineer the platform logic, or exploit API structures.</li>
          </ul>
        </LegalSection>

        {/* Section 6 */}
        <LegalSection number={6} title="Intellectual Property" icon="workspace_premium">
          <p>
            The software, user interface design, geometric brand assets, illustrations, daily challenges, and underlying algorithms are the exclusive intellectual property of CareerTrack AI and its licensors.
          </p>
          <p>
            However, **you retain full ownership and intellectual property rights over any text, resumes, or cover letters you upload or generate** on the platform. You may export and use your generated resumes and files freely for your job applications.
          </p>
        </LegalSection>

        {/* Section 7 */}
        <LegalSection number={7} title="Service Availability" icon="bolt">
          <p>
            Our platform operates on a dynamic and continuously improving architecture. To deliver new features and keep the workspace updated, we may perform scheduled maintenance or software updates.
          </p>
          <p>
            While we strive for maximum uptime, CareerTrack AI does not guarantee uninterrupted system availability or error-free operations at all times.
          </p>
        </LegalSection>

        {/* Section 8 */}
        <LegalSection number={8} title="Limitation of Liability" icon="warning">
          <p>
            To the maximum extent permitted by law, CareerTrack AI is provided on an **"as is"** and **"as available"** basis without warranties of any kind.
          </p>
          <p>
            We shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of the platform, career decisions made, or inability to access your learning history files.
          </p>
        </LegalSection>

        {/* Section 9 */}
        <LegalSection number={9} title="Updates to Terms" icon="update">
          <p>
            We may occasionally refine these terms to align with new integrations, feature updates, or industry practices. When updates are published, the date at the top will be updated.
          </p>
          <p>
            Your continued use of CareerTrack AI after terms have been revised constitutes your acceptance of the updated terms.
          </p>
        </LegalSection>

        {/* Section 10 */}
        <LegalSection number={10} title="Contact Information" icon="mail">
          <p>
            If you have questions, feedback, or need clarification regarding these Terms of Service, please reach out to our team:
          </p>
          <div className="mt-3 p-3 bg-surface-container rounded-xl flex items-center gap-3">
            <span className="material-symbols-outlined text-primary text-[18px]">email</span>
            <span className="font-mono text-xs select-all text-on-surface">legal@careertrack.ai</span>
          </div>
        </LegalSection>
      </div>
    </LegalOverlayLayout>
  );
}
